version: '3.4'

x-logging:
  &default-logging
  driver: "gelf"
  options:
    gelf-address: "udp://graylog.srv.rawm.us:12201"

services:

  web:
    build: web
    links:
      - db
      - search
    env_file: ./config
    environment:
      - PHP_TIMEZIME=America/Los_Angeles
      - MYSQL_DATABASE=scat
      - MYSQL_USER=scat
      - MYSQL_HOST_NAME=db
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ..:/var/www/html
      - ./web/conf:/etc/apache2/sites-enabled
    restart: always
    logging: *default-logging

  db:
    image: mysql:8.0.16
    env_file: ./config
    environment:
      - MYSQL_ROOT_PASSWORD=scatpass
      - MYSQL_USER=scat
    # old password auth so sphinx can access it
    command: [ mysqld, --local-infile=1, --default_authentication_plugin=mysql_native_password ]
    expose:
      - "3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    restart: always
    logging: *default-logging

  search:
    image: macbre/sphinxsearch:3.1.1
    links:
      - db
    env_file: ./config
    expose:
      - "9306"
    volumes:
      - ./search:/opt/sphinx/conf
      - searchdata:/var/data
    restart: always
    logging: *default-logging

  backup:
    build: backup
    env_file: ./config
    environment:
      - MYSQL_HOST=db
      - SCHEDULE=0 0 20 * * *
    restart: always
    logging: *default-logging

volumes:
  data:
  searchdata:
