version: '3.4'

services:

  scat:
    image: jimwins/scat
    ports:
      - "127.0.0.1:${SCAT_PORT:-9010}:9000"
    links:
      - db
      - search
    env_file: ./config
    volumes:
      - ../scat:/app
    restart: always

  ordure:
    image: jimwins/ordure
    ports:
      - "127.0.0.1:${ORDURE_PORT:-9000}:9000"
    links:
      - db
      - search
    env_file: ./config
    volumes:
      - ../ordure:/app
    restart: always

  db:
    image: mysql:8.0.16
    env_file: ./config
    environment:
      - MYSQL_ROOT_PASSWORD=scatpass
      - MYSQL_USER=scat
    # old password auth so sphinx can access it
    command: [ mysqld, --local-infile=1, --default_authentication_plugin=mysql_native_password ]
    expose:
      - "3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    restart: always

  search:
    image: macbre/sphinxsearch:3.2.1
    links:
      - db
    env_file: ./config
    expose:
      - "9306"
    volumes:
      - ./search:/opt/sphinx/conf
      - searchdata:/var/data
    restart: always

  backup:
    build: backup
    env_file: ./config
    environment:
      - MYSQL_HOST=db
      - SCHEDULE=0 0 20 * * *
    restart: always

volumes:
  data:
  searchdata:
