version: '3.1'

services:

  web:
    build: web
    links:
      - db
      - search
    env_file: ./config
    environment:
      - PHP_TIMEZIME=America/Los_Angeles
      - MYSQL_DATABASE=scat
      - MYSQL_USER=scat
      - MYSQL_HOST_NAME=db
    ports:
      - "$WEB_PORT:80"
    volumes:
      - ../scat:/var/www/html/scat
      - ../ordure:/var/www/html/ordure
      - ./web/conf:/etc/apache2/sites-enabled
    restart: always

  db:
    image: mysql:8.0.13
    env_file: ./config
    environment:
      - MYSQL_ROOT_PASSWORD=scatpass
      - MYSQL_USER=scat
    # old password auth so sphinx can access it
    command: [ mysqld, --local-infile=1, --default_authentication_plugin=mysql_native_password ]
    expose:
      - "3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    restart: always

  search:
    build: search
    entrypoint: /app/etc/run.sh
    links:
      - db
    env_file: ./config
    expose:
      - "9306"
    volumes:
      - ./search/conf:/app/etc
      - searchdata:/var/data
    restart: always

volumes:
  data:
  searchdata:
