#!/bin/sh
set -ex

docker build -t muck-lexicon .

# Create domains.txt if we don't already have one
if [ ! -f domains.txt ]; then
  cat << EOF > domains.txt
${MUCK_HOST} ordure.${MUCK_HOST} scat.${MUCK_HOST} talapoin.${MUCK_HOST}
EOF
fi

# This assumes we're using Namecheap, could be clever and use ${PROVIDER} to
# figure out which env variables to pass along

docker run -i -t --rm \
  -e "EMAIL=${EMAIL}" \
  -e "PROVIDER=${PROVIDER}" \
  -e "LEXICON_NAMECHEAP_USERNAME=${LEXICON_NAMECHEAP_USERNAME}" \
  -e "LEXICON_NAMECHEAP_TOKEN=${LEXICON_NAMECHEAP_TOKEN}" \
  -e "ACCEPT_TERMS=yes" \
  -v ${PWD}:/app \
  muck-lexicon /app/entrypoint.sh
